# baseURL is context root for asset links
baseURL: https://At-Num.github.io/
languageCode: en-us 
title: AtNum 
theme: PaperMod 
publishDir: docs
author: 
  email: "info@atnum.uk" 
  name: "AtNum" 
  location: Hudson House, 8 Albany Street, Edinburgh, EH1 3QB

menu:
  main: 
    - identifier: about 
      name: About 
      url: /about 
      weight: 30 
    - identifier: consult 
      name: Consult 
      url: /consult 
      weight: 200 
    - identifier: contact 
      name: Contact 
      url: /contact 
      weight: 130 
    - identifier: blog 
      name: Blog 
      url: /posts 
      weight: 10 
    - identifier: legal 
      name: Policies 
      url: /policies 
      weight: 200  
    - identifier: learning 
      name: Remote learning 
      url: /edu 
      weight: 1    
params: 
  customcss:
    - "css/extend.css"
  
  footer:
  - title: About
    content: >
      AtNum consulting services. Support for a broad range of services with a focus
      on secure Oracle cloud applications.
    recents: blog
    recentCount: 1
  - title: Contact Us
    contact: true

copyright: "Copyright &copy; 2022 AtNum. All Rights Reserved."
